apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
  - port: 80
  selector:
    app: payment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment-php
        image: gcr.io/cjcullen-gke-dev/payment-processor:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
data:
  payments-api-key: ZmNkYTM4YTQ2Mzc2NGRjNzUwNjk3YjU1MDQzMjM3MDhmM2YwNmM5ZQ==
kind: Secret
metadata:
  name: payments-api-key
